Repository aa-software2112/SOEN390_SimpleCamera, pull requests merged in 2019-01, with the labels that each got.

#23 Linting setup
  .travis.yml
  app/build.gradle
  app/src/main/kotlin/com/simplemobiletools/camera/activities/MainActivity.kt
  app/src/main/kotlin/com/simplemobiletools/camera/activities/SettingsActivity.kt
  app/src/main/kotlin/com/simplemobiletools/camera/dialogs/ChangeResolutionDialog.kt
  app/src/main/kotlin/com/simplemobiletools/camera/extensions/Context.kt
  app/src/main/kotlin/com/simplemobiletools/camera/helpers/PhotoProcessor.kt
  app/src/main/kotlin/com/simplemobiletools/camera/views/CameraPreview.kt
  gradlew
  ktlint.gradle
Labels: environment

#24 Env/testing #11
  .travis.yml
  app/build.gradle
  app/src/androidTest/kotlin/sample-androidTest.kt
  app/src/test/kotlin/sample-test.kt
  build.gradle
Labels: environment, test

#30 [#29] Removed linting stage, removed 2 tasks from compile stage
  .travis.yml
  build.gradle
Labels: Setup CI, task

#32 Env/add robolectric support 13
  .travis.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/test/kotlin/KotlinRobolectric.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: Setup CI

#31 Env/3 unit tests #12
  .travis.yml
  app/src/test/kotlin/KotlinJunitTest.kt
Labels: test

#33 [28] Added espresso support and single example test - to be run on ac…
  app/build.gradle
  app/src/androidTest/kotlin/com/simplemobiletools/camera/activities/MainActivityTest.kt
  build.gradle
Labels: Setup CI
