Repository aa-software2112/SOEN390_SimpleCamera, pull requests merged in 2019-02, with the labels that each got.

#52 Feat/capture time delay 20
  app/src/main/kotlin/com/simplemobiletools/camera/activities/MainActivity.kt
  app/src/main/kotlin/com/simplemobiletools/camera/helpers/Constants.kt
  app/src/main/kotlin/com/simplemobiletools/camera/views/CameraPreview.kt
  app/src/main/res/drawable/circle_shape.xml
  app/src/main/res/layout/activity_main.xml
Labels: Countdown Timer, feature

#70 [#18] Unit Tests for CountdownTimer Feature
  app/src/main/kotlin/com/simplemobiletools/camera/activities/MainActivity.kt
  app/src/test/kotlin/CountdownTimerJUnitTest.kt
  app/src/test/kotlin/KotlinRobolectric.kt
Labels: Countdown Timer, test

#77 Burstmode #76 Fix
  app/src/main/kotlin/com/simplemobiletools/camera/activities/MainActivity.kt
Labels: bug
